from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional

from app.agents.langgraph_engine import agent_graph
from app.database.memory_repository import memory_repository
from app.core.logger import logger
from app.agents.core import format_as_bullets

router = APIRouter(prefix="/agent", tags=["Agentic AI"])

class ChatRequest(BaseModel):
    query: str
    session_id: Optional[str] = "default-session"
    context: dict = {}

@router.post("/chat")
async def agent_chat(request: ChatRequest):
    """
    Main entry point for Agentic AI Chat.
    
    Uses LangGraph for deterministic orchestration.
    """
    try:
        session_id = request.session_id
        
        # 1. Save User Message to Memory
        await memory_repository.add_message(session_id, "user", request.query, "User")
        
        # 2. Get Chat History for Context
        history = await memory_repository.get_session_history(session_id, limit=6)
        
        # 3. Build Initial State for LangGraph
        initial_state = {
            "user_query": request.query,
            "session_id": session_id,
            "chat_history": history,
            "intent": None,
            "parameters": {},
            "mcp_tool_calls": [],
            "agent_response": "",
            "agent_name": None,
            "debug_info": None,
            "error": None
        }
        
        # 4. Invoke LangGraph
        logger.info(f"[Router] Invoking LangGraph for session: {session_id}")
        
        final_state = await agent_graph.ainvoke(initial_state)
        
        # 5. Extract Response
        agent_response = final_state.get("agent_response", "No response generated")
        agent_name = final_state.get("agent_name", "Unknown")
        error = final_state.get("error")
        
        # Apply bullet-point formatting
        formatted_response = format_as_bullets(agent_response)

        # 6. Build Response
        response_data = {
            "success": not error,
            "agent": agent_name,
            "intent": final_state.get("intent"),
            "response": {
                "type": "text",
                "content": formatted_response
            },
            "mcp_tool_calls": final_state.get("mcp_tool_calls", []),
            "debug_info": final_state.get("debug_info")
        }
        
        if error:
            response_data["error"] = error
        
        logger.info(f"[Router] Response generated by {agent_name}")
        
        return response_data
        
    except Exception as e:
        logger.error(f"Agent Chat Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/health")
async def health_check():
    """Check agent system health."""
    from app.mcp import mcp_server
    
    mcp_health = await mcp_server.health_check()
    
    return {
        "status": "healthy",
        "langgraph": "initialized",
        "mcp_server": mcp_health
    }
